//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kval_Ekz
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL
    {
        public int Id { get; set; }
        public string Familia { get; set; }
        public string Imya { get; set; }
        public string Otchestvo { get; set; }
        public string Pol { get; set; }
        public System.DateTime Date { get; set; }
        public string Address { get; set; }
        public Nullable<int> Id_manager { get; set; }
    
        public virtual Managers Managers { get; set; }
    }
}
